### ISSUE TITLE
Updating recipe markup does not invalidate the render cache

### ISSUE THREAD

**Issue by alesrosina** [usetrmnl/byos_laravel#131]
Currently there is no way to edit markup of a given recepie direclty in browser via admin UI - even though there is a Markup text field under recepie settings.

Is there a plan, that this markup could be edited there? Or am I supposed to edit actual file ... somewhere?

For example, I would like to customize newly added recepie for iCal calendars, but not really sure where, since I would like to use docker setup.

Am I missing sth?

Thanks for your anwser!

**Comment by bnussbau** [comment]
Hi there,
treat the example recipes as templates for now and if you want to customize, copy the markup code into a new recipe. I'll think of a way to improve that workflow

**Comment by bnussbau** [comment]
This should be fixed in 0.23.1

**Comment by abulka** [comment]
I still get cache problems in `0.32.0` - the preview within the plugin updates but the devices all show old data for days...

E.g. the pugins 
- `Little Better: Daily Challenges for a Better You`
- `Paperboy - Choose from hundreds of newspaper frontpages` 

constantly show the same image. Even the 'mirror url' renders the same thing in the browser. Other plugins that display date weather or art pic of the day etc. work ok. Maybe it depends on the plugin?

**Comment by bnussbau** [comment]
What devices are you using? Are you only using the mirror URL?
The mirror URL does not trigger display updates. for that, the /display API needs to be called by at least one device (this can also be a virtual device).

The preview is always live, the dashboard shows the last generated image.

**Comment by abulka** [comment]
> What devices are you using?

I'm using a 
- jailbroken Kindle
-  an old iPad

as devices. The mac address is not being used - its just token API based retrieval in both cases. The kindle script I developed (see below) is using the /display API. 

So I need to buy a real TRMNL or build something equivalent in hardware for LaraPaper to behave itself - seems a shame.

## Kindle Client

```sh
#!/bin/sh

# 1. KEEP AWAKE
# Force the power daemon to stay awake and keep Wi-Fi active
lipc-set-prop com.lab126.powerd preventScreenSaver 1

# CONFIG
BASE_URL="http://192.168.0.190:4567"
TOKEN="123"  # Verified token from your AMDPC curl test
DEFAULT_SLEEP=60  # Default if API doesn't provide refresh_rate
DEBUG=false  # Set to true to show debug messages

# Turn on shell tracing only if debugging
[ "$DEBUG" = true ] && set -x

eips -c

while true; do
    [ "$DEBUG" = true ] && eips 0 38 "Fetching JSON..."
    # 1. Fetch JSON using the verified header
    curl -s -H "Access-Token: $TOKEN" "$BASE_URL/api/display" -o /tmp/status.json
    
    if [ ! -s /tmp/status.json ]; then
        [ "$DEBUG" = true ] && eips 0 38 "ERR: JSON is empty or 404"
        SLEEP_TIME=$DEFAULT_SLEEP
    else
        # 2. Extract and Clean URL
        # Strips backslashes and quotes to get the raw path
        IMG_URL=$(grep -o '"image_url":"[^"]*' /tmp/status.json | cut -d'"' -f4 | sed 's/\\//g')
        
        # 3. Extract refresh_rate from JSON (if present)
        SLEEP_TIME=$(grep -o '"refresh_rate":[0-9]*' /tmp/status.json | cut -d':' -f2)
        # Use default if refresh_rate not found or empty
        [ -z "$SLEEP_TIME" ] && SLEEP_TIME=$DEFAULT_SLEEP
        
        [ "$DEBUG" = true ] && eips 0 38 "Downloading image..."

        # 3. Download the PNG
        curl -s "$IMG_URL" -o /tmp/trmnl.png
        
        # 4. Final Validation & Draw
        if [ -s /tmp/trmnl.png ]; then
            # Check magic bytes to ensure it's a real PNG, not a BMP or error page
            if head -c 8 /tmp/trmnl.png | grep -q "PNG"; then
                eips -c
                eips -g /tmp/trmnl.png
                [ "$DEBUG" = true ] && eips 0 39 "Update: $(date +%H:%M:%S)"
            else
                [ "$DEBUG" = true ] && eips 0 38 "ERR: File is not a PNG"
            fi
        else
            [ "$DEBUG" = true ] && eips 0 38 "ERR: Image download failed"
        fi
    fi

    [ "$DEBUG" = true ] && eips 0 38 "Waiting $SLEEP_TIME seconds..."
    sleep $SLEEP_TIME
done
```

**Comment by bnussbau** [comment]
> So I need to buy a real TRMNL or build something equivalent in hardware for LaraPaper to behave itself - seems a shame.

No, this is a community server, maintained solely by me, there are no such requirements.

Calling the /api/display/ endpoint should be sufficient, as mentioned in my previous comment. You can adjust the “Data is stale after (minutes)” setting on each recipe/plugin to suit your needs. Once that threshold is reached, calling the display endpoint will trigger the generation of a new image.
You can also check the container logs. they will show when a new image is being generated.
If the Kindle goes to sleep, it won’t call the display endpoint, so no new image will be generated. Also, calling the mirror URL does not trigger image generation. On your iPad you'd need to use the Mirror URL of your Kindle.

You can test with any API client, docs are here: https://docs.trmnl.com/go/diy/byos#api

**Comment by abulka** [comment]
> The mirror URL does not trigger display updates. for that, the /display API needs to be called by at least one device (this can also be a virtual device).
> ...
> calling the mirror URL does not trigger image generation.

Looking at the code of the mirror url HTML, it does indeed call `var url = baseURL + "/api/display";` so I'm not sure why it wouldn't cause image generation, once the "Data is stale after minutes" expires.  I double checked and there's only ONE code path - all requests go to /api/display.

In further testing, e.g. with the `Paperboy - Choose from hundreds of newspaper frontpages` plugin, by setting the "Data is stale after minutes" to 1 minute, the page now seems to refresh correctly, even with the mirror url, so I'm happy.
